"""
Field schema definitions for template-specific VLM recognition.

This module defines the structure of document fields, template schemas,
and Traditional Chinese prompt templates for VLM inference.

*** AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ***
*** Generated by update_configs.py at 2026-02-24 09:57:56 ***
*** Run `python update_configs.py` to regenerate this file ***
"""

from dataclasses import dataclass
from typing import List, Optional, Dict
import logging

logger = logging.getLogger(__name__)


@dataclass
class FieldSchema:
    """Defines the structure and recognition requirements for a single document field.

    Attributes:
        field_id: Unique identifier (e.g., "company_number1", "VX1", "small", "version", "person_number1")
        field_type: Recognition type - one of: "title", "version", "checkbox", "stamp", "text", "number", "person_number"
        template_id: Parent template identifier (contractor_1, contractor_2, enterprise_1)
        description: Human-readable field description
        prompt_template_key: Key to lookup prompt in PROMPT_TEMPLATES dict
        predefined_value: For title fields only - predefined text to output without VLM inference
    """

    field_id: str
    field_type: str  # "title" | "version" | "checkbox" | "stamp" | "text" | "number" | "person_number"
    template_id: str
    description: str
    prompt_template_key: str
    predefined_value: Optional[str] = None

    def validate(self):
        """Validate field schema consistency.

        Raises:
            AssertionError: If validation fails
        """
        assert self.field_type in {"title", "version", "checkbox", "stamp", "text", "number", "person_number"}, \
            f"Invalid field_type: {self.field_type}"

        if self.field_type == "title":
            assert self.predefined_value is not None, \
                f"Title field {self.field_id} must have predefined_value"
        else:
            assert self.predefined_value is None, \
                f"Non-title field {self.field_id} must have null predefined_value"

    def get_prompt(self, prompt_templates: Dict[str, str]) -> str:
        """Get the VLM prompt for this field.

        Args:
            prompt_templates: Dictionary mapping prompt_template_key to prompt text

        Returns:
            VLM prompt string, or empty string for title fields
        """
        if self.field_type == "title":
            return ""  # No VLM inference for titles

        if self.prompt_template_key not in prompt_templates:
            logger.warning(f"Prompt template key '{self.prompt_template_key}' not found, using generic prompt")
            return prompt_templates.get("generic", "")

        return prompt_templates[self.prompt_template_key]


@dataclass
class TemplateSchema:
    """Defines the complete set of fields for a document template type.

    Attributes:
        template_id: Template identifier (contractor_1, contractor_2, enterprise_1)
        field_schemas: Ordered list of field definitions
        title_field_id: Field ID of the title field for this template
    """

    template_id: str
    field_schemas: List[FieldSchema]
    title_field_id: str

    @property
    def field_count(self) -> int:
        """Get total number of fields in this template."""
        return len(self.field_schemas)

    def validate(self):
        """Validate template schema consistency.

        Raises:
            AssertionError: If validation fails
        """
        # Check for duplicate field IDs
        field_ids = [f.field_id for f in self.field_schemas]
        assert len(field_ids) == len(set(field_ids)), \
            f"Duplicate field IDs in template {self.template_id}"

        # Validate title field exists
        title_fields = [f for f in self.field_schemas if f.field_id == self.title_field_id]
        assert len(title_fields) == 1, \
            f"Template {self.template_id} must have exactly one title field with ID {self.title_field_id}"
        assert title_fields[0].field_type == "title", \
            f"Title field {self.title_field_id} must have field_type='title'"

        # Validate all fields
        for field in self.field_schemas:
            field.validate()
            assert field.template_id == self.template_id, \
                f"Field {field.field_id} template_id mismatch"

    def get_field_by_id(self, field_id: str) -> Optional[FieldSchema]:
        """Retrieve field schema by field_id.

        Args:
            field_id: Field identifier to lookup

        Returns:
            FieldSchema if found, None otherwise
        """
        for field in self.field_schemas:
            if field.field_id == field_id:
                return field
        return None


# OCR prompt templates optimized for Ollama glm-ocr
# IMPORTANT: glm-ocr is a pure OCR model. Long/complex prompts get echoed back as output.
# Keep prompts SHORT (1-2 lines max) to avoid prompt echo in results.
# Post-processing handles: $$ removal, simplified→traditional Chinese, number formatting.
PROMPT_TEMPLATES: Dict[str, str] = {
    # Version field: 8-digit version number (e.g., 20250417)
    "version": "這是版本號碼，格式為8位數字。請辨識並只輸出8個數字，欄位如果空白或辨識不到內容就輸出空白",

    # Checkbox field: detect check marks in circle/square
    "checkbox": "請描述框內是否有打勾、打叉或手寫標記",

    # Stamp/seal field: detect and read stamp content
    "stamp": "請辨識印章上的繁體中文文字",

    # Text field: handwritten or printed Traditional Chinese text
    "text": "請辨識圖片中的繁體中文文字",

    # Number field: digits (company number, year, month, date)
    "number": "請辨識圖片中的數字，只輸出數字",

    # Person number field: Taiwan ID (1 letter + 9 digits)
    "person_number": "請辨識身分證字號，格式為左到右1個英文字母加9個數字",

    # Generic fallback prompt
    "generic": "請辨識圖片中的繁體中文文字內容",
}


# contractor_1: 14 fields
# IMPORTANT: Order MUST match config.json ROI order for correct zip() alignment
CONTRACTOR_1_FIELDS = [
    FieldSchema(
        field_id="VX1",
        field_type="checkbox",
        template_id="contractor_1",
        description="同意/不同意勾選框1",
        prompt_template_key="checkbox",
        predefined_value=None
    ),
    FieldSchema(
        field_id="contractor_1_title",
        field_type="title",
        template_id="contractor_1",
        description="文件標題",
        prompt_template_key="",
        predefined_value="企業負責人電信信評報告之使用授權書"
    ),
    FieldSchema(
        field_id="person1",
        field_type="text",
        template_id="contractor_1",
        description="負責人姓名欄位1",
        prompt_template_key="text",
        predefined_value=None
    ),
    FieldSchema(
        field_id="company1",
        field_type="text",
        template_id="contractor_1",
        description="公司名稱欄位1",
        prompt_template_key="text",
        predefined_value=None
    ),
    FieldSchema(
        field_id="VX2",
        field_type="checkbox",
        template_id="contractor_1",
        description="同意/不同意勾選框2",
        prompt_template_key="checkbox",
        predefined_value=None
    ),
    FieldSchema(
        field_id="company2",
        field_type="text",
        template_id="contractor_1",
        description="公司名稱欄位2",
        prompt_template_key="text",
        predefined_value=None
    ),
    FieldSchema(
        field_id="company_number1",
        field_type="number",
        template_id="contractor_1",
        description="統一編號欄位1",
        prompt_template_key="number",
        predefined_value=None
    ),
    FieldSchema(
        field_id="person2",
        field_type="text",
        template_id="contractor_1",
        description="負責人姓名欄位2",
        prompt_template_key="text",
        predefined_value=None
    ),
    FieldSchema(
        field_id="person_number1",
        field_type="person_number",
        template_id="contractor_1",
        description="負責人身分證字號",
        prompt_template_key="person_number",
        predefined_value=None
    ),
    FieldSchema(
        field_id="big1",
        field_type="stamp",
        template_id="contractor_1",
        description="大印章區域",
        prompt_template_key="stamp",
        predefined_value=None
    ),
    FieldSchema(
        field_id="year",
        field_type="number",
        template_id="contractor_1",
        description="年份欄位",
        prompt_template_key="number",
        predefined_value=None
    ),
    FieldSchema(
        field_id="month",
        field_type="number",
        template_id="contractor_1",
        description="月份欄位",
        prompt_template_key="number",
        predefined_value=None
    ),
    FieldSchema(
        field_id="date",
        field_type="number",
        template_id="contractor_1",
        description="日期欄位",
        prompt_template_key="number",
        predefined_value=None
    ),
    FieldSchema(
        field_id="version",
        field_type="version",
        template_id="contractor_1",
        description="版本號碼欄位",
        prompt_template_key="version",
        predefined_value=None
    ),
]

# contractor_2: 3 fields
# IMPORTANT: Order MUST match config.json ROI order for correct zip() alignment
CONTRACTOR_2_FIELDS = [
    FieldSchema(
        field_id="contractor_2_title",
        field_type="title",
        template_id="contractor_2",
        description="文件標題",
        prompt_template_key="",
        predefined_value="個人資料特定目的外用告知事項暨同意書"
    ),
    FieldSchema(
        field_id="small1",
        field_type="stamp",
        template_id="contractor_2",
        description="小印章區域",
        prompt_template_key="stamp",
        predefined_value=None
    ),
    FieldSchema(
        field_id="version",
        field_type="version",
        template_id="contractor_2",
        description="版本號碼欄位",
        prompt_template_key="version",
        predefined_value=None
    ),
]

# enterprise_1: 15 fields
# IMPORTANT: Order MUST match config.json ROI order for correct zip() alignment
ENTERPRISE_1_FIELDS = [
    FieldSchema(
        field_id="VX1",
        field_type="checkbox",
        template_id="enterprise_1",
        description="同意/不同意勾選框1",
        prompt_template_key="checkbox",
        predefined_value=None
    ),
    FieldSchema(
        field_id="enterprise_1_title",
        field_type="title",
        template_id="enterprise_1",
        description="文件標題",
        prompt_template_key="",
        predefined_value="企業電信信評報告之使用授權書"
    ),
    FieldSchema(
        field_id="person1",
        field_type="text",
        template_id="enterprise_1",
        description="負責人姓名欄位1",
        prompt_template_key="text",
        predefined_value=None
    ),
    FieldSchema(
        field_id="company1",
        field_type="text",
        template_id="enterprise_1",
        description="公司名稱欄位1",
        prompt_template_key="text",
        predefined_value=None
    ),
    FieldSchema(
        field_id="VX2",
        field_type="checkbox",
        template_id="enterprise_1",
        description="同意/不同意勾選框2",
        prompt_template_key="checkbox",
        predefined_value=None
    ),
    FieldSchema(
        field_id="company2",
        field_type="text",
        template_id="enterprise_1",
        description="公司名稱欄位2",
        prompt_template_key="text",
        predefined_value=None
    ),
    FieldSchema(
        field_id="person2",
        field_type="text",
        template_id="enterprise_1",
        description="負責人姓名欄位2",
        prompt_template_key="text",
        predefined_value=None
    ),
    FieldSchema(
        field_id="company_number1",
        field_type="number",
        template_id="enterprise_1",
        description="統一編號欄位1",
        prompt_template_key="number",
        predefined_value=None
    ),
    FieldSchema(
        field_id="year",
        field_type="number",
        template_id="enterprise_1",
        description="年份欄位",
        prompt_template_key="number",
        predefined_value=None
    ),
    FieldSchema(
        field_id="month",
        field_type="number",
        template_id="enterprise_1",
        description="月份欄位",
        prompt_template_key="number",
        predefined_value=None
    ),
    FieldSchema(
        field_id="date",
        field_type="number",
        template_id="enterprise_1",
        description="日期欄位",
        prompt_template_key="number",
        predefined_value=None
    ),
    FieldSchema(
        field_id="big1",
        field_type="stamp",
        template_id="enterprise_1",
        description="大印章區域",
        prompt_template_key="stamp",
        predefined_value=None
    ),
    FieldSchema(
        field_id="small1",
        field_type="stamp",
        template_id="enterprise_1",
        description="小印章區域",
        prompt_template_key="stamp",
        predefined_value=None
    ),
    FieldSchema(
        field_id="address",
        field_type="text",
        template_id="enterprise_1",
        description="公司地址欄位",
        prompt_template_key="text",
        predefined_value=None
    ),
    FieldSchema(
        field_id="version",
        field_type="version",
        template_id="enterprise_1",
        description="版本號碼欄位",
        prompt_template_key="version",
        predefined_value=None
    ),
]

# Global template schemas mapping
TEMPLATE_SCHEMAS: Dict[str, TemplateSchema] = {
    "contractor_1": TemplateSchema(
        template_id="contractor_1",
        field_schemas=CONTRACTOR_1_FIELDS,
        title_field_id="contractor_1_title"
    ),
    "contractor_2": TemplateSchema(
        template_id="contractor_2",
        field_schemas=CONTRACTOR_2_FIELDS,
        title_field_id="contractor_2_title"
    ),
    "enterprise_1": TemplateSchema(
        template_id="enterprise_1",
        field_schemas=ENTERPRISE_1_FIELDS,
        title_field_id="enterprise_1_title"
    ),
}


# Validate all template schemas on module load
def _validate_all_schemas():
    """Validate all template schemas on module import."""
    for template_id, schema in TEMPLATE_SCHEMAS.items():
        try:
            schema.validate()
            logger.debug(f"Template schema '{template_id}' validated successfully ({schema.field_count} fields)")
        except AssertionError as e:
            logger.error(f"Template schema '{template_id}' validation failed: {e}")
            raise


# Run validation on import
_validate_all_schemas()
